apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-client-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app-client
  template:
    metadata:
      labels:
        app: my-app-client
    spec:
      containers:
      - name: my-app-client
        image: myusername/my-app-client:latest
        ports:
        - containerPort: 80
