apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app-server
  template:
    metadata:
      labels:
        app: my-app-server
    spec:
      containers:
      - name: my-app-server
        image: myusername/my-app-server:latest
        ports:
        - containerPort: 3000
