apiVersion: v1
kind: Service
metadata:
  name: my-app-server-service
spec:
  selector:
    app: my-app-server
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer
